const items = [
    "Chromatic Loopscape",
    "Solar Bloom",
    "Neon Handscape",
    "Echo Discs",
    "Void Gaze",
    "Gravity Sync",
    "Heat Coze",
    "Fractal Mirage",
    "Sonic Horizon",
    "Dream Circuit",
    "Lunar Mesh",
    "Radiant Dusk",
    "Pixel Drift",
    "Vortex Bloom",
    "Shadow Static",
    "Crimson Phase",
    "Retro Cascade",
    "Photon Fold",
    "Zenith Flow",
    "Aura Weave",
    "Quantum Pulse",
    "Cyberglow",
    "Infrared Drift",
    "Plasma Orb",
    "Glitch Garden",
  ];
  
  export default items;